; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = ./boards

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = VAAMrp2350_FOCSPE
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 1m
board_build.usbstack = tinyusb
board_build.variants_dir = ./variants
board_build.variant = vaam_rp2350spefoc
build_flags =
	-DHUB75_SIZE=4040
	-DPCB_LAYOUT_V2=1
	-DHUB75_BCM=1
	-DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS=1
lib_deps =
	LittleFS
	WebServer
	https://github.com/sfranzyshen/ESP-Arduino-Lua.git
	Links2004/WebSockets
	Adafruit GFX Library
	https://github.com/RadicalTray/Arduino_10BASE_T1S.git
	https://github.com/bblanchon/ArduinoJson
	256dpi/MQTT
